const BASE_URL = "https://git.tyrantg.com/tyrantgenesis/hikerViewRules/raw/master/"
const collection_password = "海阔视界，首页频道合集￥home_rule_url￥"
const rule_password = "海阔视界规则分享，当前分享的是：小程序￥home_rule_v2￥"

const baseParse = _ => {
    let res = {};
    let d = [];
    const script = fetch(MY_URL);
    const data_json = fetch('hiker://files/TyrantG/data/base.json');
    const data = JSON.parse(data_json)
    let fst_rule_list = []
    let snd_rule_list = []

    eval(script);

    d.push({
        pic_url: `data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIj8+CjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cu
dzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNDk1IiBoZWlnaHQ9IjE5NSIgdmll
d0JveD0iMCAwIDQ5NSAxOTUiIGZpbGw9Im5vbmUiPgogICAgPHN0eWxlPgog
ICAgICAgIC5oZWFkZXIgewogICAgICAgIGZvbnQ6IDYwMCAxOHB4ICdTZWdv
ZSBVSScsIFVidW50dSwgU2Fucy1TZXJpZjsKICAgICAgICBmaWxsOiAjNzBh
NWZkOwogICAgICAgIGFuaW1hdGlvbjogZmFkZUluQW5pbWF0aW9uIDAuOHMg
ZWFzZS1pbi1vdXQgZm9yd2FyZHM7CiAgICAgICAgfQoKICAgICAgICAuc3Rh
dCB7CiAgICAgICAgZm9udDogNjAwIDE0cHggJ1NlZ29lIFVJJywgVWJ1bnR1
LCAiSGVsdmV0aWNhIE5ldWUiLCBTYW5zLVNlcmlmOyBmaWxsOiAjMzhiZGFl
OwogICAgICAgIH0KICAgICAgICAuc3RhZ2dlciB7CiAgICAgICAgb3BhY2l0
eTogMDsKICAgICAgICBhbmltYXRpb246IGZhZGVJbkFuaW1hdGlvbiAwLjNz
IGVhc2UtaW4tb3V0IGZvcndhcmRzOwogICAgICAgIH0KICAgICAgICAucmFu
ay10ZXh0IHsKICAgICAgICBmb250OiA4MDAgMjRweCAnU2Vnb2UgVUknLCBV
YnVudHUsIFNhbnMtU2VyaWY7IGZpbGw6ICMzOGJkYWU7CiAgICAgICAgYW5p
bWF0aW9uOiBzY2FsZUluQW5pbWF0aW9uIDAuM3MgZWFzZS1pbi1vdXQgZm9y
d2FyZHM7CiAgICAgICAgfQoKICAgICAgICAuYm9sZCB7IGZvbnQtd2VpZ2h0
OiA3MDAgfQogICAgICAgIC5pY29uIHsKICAgICAgICBmaWxsOiAjYmY5MWYz
OwogICAgICAgIGRpc3BsYXk6IGJsb2NrOwogICAgICAgIH0KCiAgICAgICAg
LnJhbmstY2lyY2xlLXJpbSB7CiAgICAgICAgc3Ryb2tlOiAjNzBhNWZkOwog
ICAgICAgIGZpbGw6IG5vbmU7CiAgICAgICAgc3Ryb2tlLXdpZHRoOiA2Owog
ICAgICAgIG9wYWNpdHk6IDAuMjsKICAgICAgICB9CiAgICAgICAgLnJhbmst
Y2lyY2xlIHsKICAgICAgICBzdHJva2U6ICM3MGE1ZmQ7CiAgICAgICAgc3Ry
b2tlLWRhc2hhcnJheTogMjUwOwogICAgICAgIGZpbGw6IG5vbmU7CiAgICAg
ICAgc3Ryb2tlLXdpZHRoOiA2OwogICAgICAgIHN0cm9rZS1saW5lY2FwOiBy
b3VuZDsKICAgICAgICBvcGFjaXR5OiAwLjg7CiAgICAgICAgdHJhbnNmb3Jt
LW9yaWdpbjogLTEwcHggOHB4OwogICAgICAgIHRyYW5zZm9ybTogcm90YXRl
KC05MGRlZyk7CiAgICAgICAgYW5pbWF0aW9uOiByYW5rQW5pbWF0aW9uIDFz
IGZvcndhcmRzIGVhc2UtaW4tb3V0OwogICAgICAgIH0KCiAgICAgICAgQGtl
eWZyYW1lcyByYW5rQW5pbWF0aW9uIHsKICAgICAgICBmcm9tIHsKICAgICAg
ICBzdHJva2UtZGFzaG9mZnNldDogMjUxLjMyNzQxMjI4NzE4MzQ1OwogICAg
ICAgIH0KICAgICAgICB0byB7CiAgICAgICAgc3Ryb2tlLWRhc2hvZmZzZXQ6
IDEyNy42NjA2MTI1NTgyODc7CiAgICAgICAgfQogICAgICAgIH0KCgoKCiAg
ICAgICAgLyogQW5pbWF0aW9ucyAqLwogICAgICAgIEBrZXlmcmFtZXMgc2Nh
bGVJbkFuaW1hdGlvbiB7CiAgICAgICAgZnJvbSB7CiAgICAgICAgdHJhbnNm
b3JtOiB0cmFuc2xhdGUoLTVweCwgNXB4KSBzY2FsZSgwKTsKICAgICAgICB9
CiAgICAgICAgdG8gewogICAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlKC01
cHgsIDVweCkgc2NhbGUoMSk7CiAgICAgICAgfQogICAgICAgIH0KICAgICAg
ICBAa2V5ZnJhbWVzIGZhZGVJbkFuaW1hdGlvbiB7CiAgICAgICAgZnJvbSB7
CiAgICAgICAgb3BhY2l0eTogMDsKICAgICAgICB9CiAgICAgICAgdG8gewog
ICAgICAgIG9wYWNpdHk6IDE7CiAgICAgICAgfQogICAgICAgIH0KCgogICAg
PC9zdHlsZT4KCiAgICB1bmRlZmluZWQKCiAgICA8cmVjdCB4PSIwLjUiIHk9
IjAuNSIgcng9IjQuNSIgaGVpZ2h0PSI5OSUiIHN0cm9rZT0iI2U0ZTJlMiIg
d2lkdGg9IjQ5NCIgZmlsbD0iIzFhMWIyNyIgc3Ryb2tlLW9wYWNpdHk9IjEi
Lz4KCgogICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUsIDM1KSI+CiAg
ICAgICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCwgMCkiPgogICAgICAg
ICAgICA8dGV4dCB4PSIwIiB5PSIwIiBjbGFzcz0iaGVhZGVyIj5UeXJhbnRH
ZW5lc2lzJyBHaXRIdWIgU3RhdHM8L3RleHQ+CiAgICAgICAgPC9nPgogICAg
PC9nPgoKCiAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLCA1NSkiPgoK
ICAgICAgICA8ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSg0MDAsIDQ3LjUpIj4K
ICAgICAgICAgICAgPGNpcmNsZSBjbGFzcz0icmFuay1jaXJjbGUtcmltIiBj
eD0iLTEwIiBjeT0iOCIgcj0iNDAiLz4KICAgICAgICAgICAgPGNpcmNsZSBj
bGFzcz0icmFuay1jaXJjbGUiIGN4PSItMTAiIGN5PSI4IiByPSI0MCIvPgog
ICAgICAgICAgICA8ZyBjbGFzcz0icmFuay10ZXh0Ij4KICAgICAgICAgICAg
ICAgIDx0ZXh0IHg9IjAiIHk9IjAiIGFsaWdubWVudC1iYXNlbGluZT0iY2Vu
dHJhbCIgZG9taW5hbnQtYmFzZWxpbmU9ImNlbnRyYWwiIHRleHQtYW5jaG9y
PSJtaWRkbGUiPgogICAgICAgICAgICAgICAgICAgIEErCiAgICAgICAgICAg
ICAgICA8L3RleHQ+CiAgICAgICAgICAgIDwvZz4KICAgICAgICA8L2c+Cgog
ICAgICAgIDxzdmcgeD0iMCIgeT0iMCI+CiAgICAgICAgICAgIDxnIHRyYW5z
Zm9ybT0idHJhbnNsYXRlKDAsIDApIj4KICAgICAgICAgICAgICAgIDxnIGNs
YXNzPSJzdGFnZ2VyIiBzdHlsZT0iYW5pbWF0aW9uLWRlbGF5OiA0NTBtcyIg
dHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUsIDApIj4KCiAgICAgICAgICAgICAg
ICAgICAgPHN2ZyBkYXRhLXRlc3RpZD0iaWNvbiIgY2xhc3M9Imljb24iIHZp
ZXdCb3g9IjAgMCAxNiAxNiIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMTYiIGhl
aWdodD0iMTYiPgogICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBmaWxs
LXJ1bGU9ImV2ZW5vZGQiIGQ9Ik04IC4yNWEuNzUuNzUgMCAwMS42NzMuNDE4
bDEuODgyIDMuODE1IDQuMjEuNjEyYS43NS43NSAwIDAxLjQxNiAxLjI3OWwt
My4wNDYgMi45Ny43MTkgNC4xOTJhLjc1Ljc1IDAgMDEtMS4wODguNzkxTDgg
MTIuMzQ3bC0zLjc2NiAxLjk4YS43NS43NSAwIDAxLTEuMDg4LS43OWwuNzIt
NC4xOTRMLjgxOCA2LjM3NGEuNzUuNzUgMCAwMS40MTYtMS4yOGw0LjIxLS42
MTFMNy4zMjcuNjY4QS43NS43NSAwIDAxOCAuMjV6bTAgMi40NDVMNi42MTUg
NS41YS43NS43NSAwIDAxLS41NjQuNDFsLTMuMDk3LjQ1IDIuMjQgMi4xODRh
Ljc1Ljc1IDAgMDEuMjE2LjY2NGwtLjUyOCAzLjA4NCAyLjc2OS0xLjQ1NmEu
NzUuNzUgMCAwMS42OTggMGwyLjc3IDEuNDU2LS41My0zLjA4NGEuNzUuNzUg
MCAwMS4yMTYtLjY2NGwyLjI0LTIuMTgzLTMuMDk2LS40NWEuNzUuNzUgMCAw
MS0uNTY0LS40MUw4IDIuNjk0di4wMDF6Ii8+CiAgICAgICAgICAgICAgICAg
ICAgPC9zdmc+CgogICAgICAgICAgICAgICAgICAgIDx0ZXh0IGNsYXNzPSJz
dGF0IGJvbGQiIHg9IjI1IiB5PSIxMi41Ij5Ub3RhbCBTdGFyczo8L3RleHQ+
CiAgICAgICAgICAgICAgICAgICAgPHRleHQgY2xhc3M9InN0YXQiIHg9IjE5
MCIgeT0iMTIuNSI+ODwvdGV4dD4KICAgICAgICAgICAgICAgIDwvZz4KICAg
ICAgICAgICAgPC9nPjxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsIDI1KSI+
CiAgICAgICAgICAgIDxnIGNsYXNzPSJzdGFnZ2VyIiBzdHlsZT0iYW5pbWF0
aW9uLWRlbGF5OiA2MDBtcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUsIDAp
Ij4KCiAgICAgICAgICAgICAgICA8c3ZnIGRhdGEtdGVzdGlkPSJpY29uIiBj
bGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDE2IDE2IiB2ZXJzaW9uPSIxLjEi
IHdpZHRoPSIxNiIgaGVpZ2h0PSIxNiI+CiAgICAgICAgICAgICAgICAgICAg
PHBhdGggZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMS42NDMgMy4xNDNMLjQy
NyAxLjkyN0EuMjUuMjUgMCAwMDAgMi4xMDRWNS43NWMwIC4xMzguMTEyLjI1
LjI1LjI1aDMuNjQ2YS4yNS4yNSAwIDAwLjE3Ny0uNDI3TDIuNzE1IDQuMjE1
YTYuNSA2LjUgMCAxMS0xLjE4IDQuNDU4Ljc1Ljc1IDAgMTAtMS40OTMuMTU0
IDguMDAxIDguMDAxIDAgMTAxLjYtNS42ODR6TTcuNzUgNGEuNzUuNzUgMCAw
MS43NS43NXYyLjk5MmwyLjAyOC44MTJhLjc1Ljc1IDAgMDEtLjU1NyAxLjM5
MmwtMi41LTFBLjc1Ljc1IDAgMDE3IDguMjV2LTMuNUEuNzUuNzUgMCAwMTcu
NzUgNHoiLz4KICAgICAgICAgICAgICAgIDwvc3ZnPgoKICAgICAgICAgICAg
ICAgIDx0ZXh0IGNsYXNzPSJzdGF0IGJvbGQiIHg9IjI1IiB5PSIxMi41Ij5U
b3RhbCBDb21taXRzICgyMDIxKTo8L3RleHQ+CiAgICAgICAgICAgICAgICA8
dGV4dCBjbGFzcz0ic3RhdCIgeD0iMTkwIiB5PSIxMi41Ij42MDwvdGV4dD4K
ICAgICAgICAgICAgPC9nPgogICAgICAgIDwvZz48ZyB0cmFuc2Zvcm09InRy
YW5zbGF0ZSgwLCA1MCkiPgogICAgICAgICAgICA8ZyBjbGFzcz0ic3RhZ2dl
ciIgc3R5bGU9ImFuaW1hdGlvbi1kZWxheTogNzUwbXMiIHRyYW5zZm9ybT0i
dHJhbnNsYXRlKDI1LCAwKSI+CgogICAgICAgICAgICAgICAgPHN2ZyBkYXRh
LXRlc3RpZD0iaWNvbiIgY2xhc3M9Imljb24iIHZpZXdCb3g9IjAgMCAxNiAx
NiIgdmVyc2lvbj0iMS4xIiB3aWR0aD0iMTYiIGhlaWdodD0iMTYiPgogICAg
ICAgICAgICAgICAgICAgIDxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0i
TTcuMTc3IDMuMDczTDkuNTczLjY3N0EuMjUuMjUgMCAwMTEwIC44NTR2NC43
OTJhLjI1LjI1IDAgMDEtLjQyNy4xNzdMNy4xNzcgMy40MjdhLjI1LjI1IDAg
MDEwLS4zNTR6TTMuNzUgMi41YS43NS43NSAwIDEwMCAxLjUuNzUuNzUgMCAw
MDAtMS41em0tMi4yNS43NWEyLjI1IDIuMjUgMCAxMTMgMi4xMjJ2NS4yNTZh
Mi4yNTEgMi4yNTEgMCAxMS0xLjUgMFY1LjM3MkEyLjI1IDIuMjUgMCAwMTEu
NSAzLjI1ek0xMSAyLjVoLTFWNGgxYTEgMSAwIDAxMSAxdjUuNjI4YTIuMjUx
IDIuMjUxIDAgMTAxLjUgMFY1QTIuNSAyLjUgMCAwMDExIDIuNXptMSAxMC4y
NWEuNzUuNzUgMCAxMTEuNSAwIC43NS43NSAwIDAxLTEuNSAwek0zLjc1IDEy
YS43NS43NSAwIDEwMCAxLjUuNzUuNzUgMCAwMDAtMS41eiIvPgogICAgICAg
ICAgICAgICAgPC9zdmc+CgogICAgICAgICAgICAgICAgPHRleHQgY2xhc3M9
InN0YXQgYm9sZCIgeD0iMjUiIHk9IjEyLjUiPlRvdGFsIFBSczo8L3RleHQ+
CiAgICAgICAgICAgICAgICA8dGV4dCBjbGFzcz0ic3RhdCIgeD0iMTkwIiB5
PSIxMi41Ij4yPC90ZXh0PgogICAgICAgICAgICA8L2c+CiAgICAgICAgPC9n
PjxnIHRyYW5zZm9ybT0idHJhbnNsYXRlKDAsIDc1KSI+CiAgICAgICAgICAg
IDxnIGNsYXNzPSJzdGFnZ2VyIiBzdHlsZT0iYW5pbWF0aW9uLWRlbGF5OiA5
MDBtcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUsIDApIj4KCiAgICAgICAg
ICAgICAgICA8c3ZnIGRhdGEtdGVzdGlkPSJpY29uIiBjbGFzcz0iaWNvbiIg
dmlld0JveD0iMCAwIDE2IDE2IiB2ZXJzaW9uPSIxLjEiIHdpZHRoPSIxNiIg
aGVpZ2h0PSIxNiI+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZmlsbC1y
dWxlPSJldmVub2RkIiBkPSJNOCAxLjVhNi41IDYuNSAwIDEwMCAxMyA2LjUg
Ni41IDAgMDAwLTEzek0wIDhhOCA4IDAgMTExNiAwQTggOCAwIDAxMCA4em05
IDNhMSAxIDAgMTEtMiAwIDEgMSAwIDAxMiAwem0tLjI1LTYuMjVhLjc1Ljc1
IDAgMDAtMS41IDB2My41YS43NS43NSAwIDAwMS41IDB2LTMuNXoiLz4KICAg
ICAgICAgICAgICAgIDwvc3ZnPgoKICAgICAgICAgICAgICAgIDx0ZXh0IGNs
YXNzPSJzdGF0IGJvbGQiIHg9IjI1IiB5PSIxMi41Ij5Ub3RhbCBJc3N1ZXM6
PC90ZXh0PgogICAgICAgICAgICAgICAgPHRleHQgY2xhc3M9InN0YXQiIHg9
IjE5MCIgeT0iMTIuNSI+MjwvdGV4dD4KICAgICAgICAgICAgPC9nPgogICAg
ICAgIDwvZz48ZyB0cmFuc2Zvcm09InRyYW5zbGF0ZSgwLCAxMDApIj4KICAg
ICAgICAgICAgPGcgY2xhc3M9InN0YWdnZXIiIHN0eWxlPSJhbmltYXRpb24t
ZGVsYXk6IDEwNTBtcyIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMjUsIDApIj4K
CiAgICAgICAgICAgICAgICA8c3ZnIGRhdGEtdGVzdGlkPSJpY29uIiBjbGFz
cz0iaWNvbiIgdmlld0JveD0iMCAwIDE2IDE2IiB2ZXJzaW9uPSIxLjEiIHdp
ZHRoPSIxNiIgaGVpZ2h0PSIxNiI+CiAgICAgICAgICAgICAgICAgICAgPHBh
dGggZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMiAyLjVBMi41IDIuNSAwIDAx
NC41IDBoOC43NWEuNzUuNzUgMCAwMS43NS43NXYxMi41YS43NS43NSAwIDAx
LS43NS43NWgtMi41YS43NS43NSAwIDExMC0xLjVoMS43NXYtMmgtOGExIDEg
MCAwMC0uNzE0IDEuNy43NS43NSAwIDAxLTEuMDcyIDEuMDVBMi40OTUgMi40
OTUgMCAwMTIgMTEuNXYtOXptMTAuNS0xVjloLThjLS4zNTYgMC0uNjk0LjA3
NC0xIC4yMDhWMi41YTEgMSAwIDAxMS0xaDh6TTUgMTIuMjV2My4yNWEuMjUu
MjUgMCAwMC40LjJsMS40NS0xLjA4N2EuMjUuMjUgMCAwMS4zIDBMOC42IDE1
LjdhLjI1LjI1IDAgMDAuNC0uMnYtMy4yNWEuMjUuMjUgMCAwMC0uMjUtLjI1
aC0zLjVhLjI1LjI1IDAgMDAtLjI1LjI1eiIvPgogICAgICAgICAgICAgICAg
PC9zdmc+CgogICAgICAgICAgICAgICAgPHRleHQgY2xhc3M9InN0YXQgYm9s
ZCIgeD0iMjUiIHk9IjEyLjUiPkNvbnRyaWJ1dGVkIHRvOjwvdGV4dD4KICAg
ICAgICAgICAgICAgIDx0ZXh0IGNsYXNzPSJzdGF0IiB4PSIxOTAiIHk9IjEy
LjUiPjU8L3RleHQ+CiAgICAgICAgICAgIDwvZz4KICAgICAgICA8L2c+CiAg
ICAgICAgPC9zdmc+CgogICAgPC9nPgo8L3N2Zz4K`,
        url: "https://github.com/TyrantG",
        col_type: 'pic_1_full'
    });

    data.forEach(rule => {
        fst_rule_list = []
        rule.data.forEach(item => {
            item.rules.forEach(each => {
                fst_rule_list.push(each.rule)
            })
        })
        writeFile("hiker://files/TyrantG/Temporary/"+rule.title+".json", JSON.stringify(fst_rule_list));

        d.push({
            title: rule.title,
            url: "rule://"+base64Encode(collection_password+"hiker://files/TyrantG/Temporary/"+rule.title+".json").replace(/\n/g, ''),
            col_type: 'text_center_1'
        });

        rule.data.forEach(item => {
            snd_rule_list = []
            item.rules.forEach(each => {
                snd_rule_list.push(each.rule)
            })
            writeFile("hiker://files/TyrantG/Temporary/"+rule.title+"/"+item.title+".json", JSON.stringify(snd_rule_list));
            d.push({
                title: item.title,
                url: "rule://"+base64Encode(collection_password+"hiker://files/TyrantG/Temporary/"+rule.title+"/"+item.title+".json").replace(/\n/g, ''),
                col_type: 'text_2'
            });
            item.rules.forEach(each => {
                d.push({
                    title: each.title,
                    url: "rule://"+base64Encode(rule_password+JSON.stringify(each.rule)).replace(/\n/g, ''),
                    col_type: 'flex_button'
                })
            })
            d.push({
                col_type: 'line'
            });
        })

        d.push({
            col_type: 'line_blank'
        });
    })

    res.data = d;
    setHomeResult(res);
}